# Generated by Django 5.2.11 on 2026-03-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("summary", models.TextField()),
                ("files_modified", models.JSONField(default=list)),
                ("commits", models.JSONField(default=list)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("api_request", "API 요청"),
                            ("management_cmd", "관리 명령어"),
                            ("deployment", "배포"),
                            ("error", "에러"),
                            ("cover_generation", "커버 이미지 생성"),
                            ("content_import", "컨텐츠 임포트"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("detail", models.JSONField(default=dict)),
                ("status", models.CharField(max_length=20)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["log_type", "-created_at"],
                        name="operations__log_typ_8b5e42_idx",
                    )
                ],
            },
        ),
    ]
