# Generated by Django 5.2.11 on 2026-03-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchitectureConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#6366F1", max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ArchitectureEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("organization", models.CharField(max_length=100)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "decoder_type",
                    models.CharField(
                        choices=[
                            ("dense", "Dense"),
                            ("sparse_moe", "Sparse MoE"),
                            ("sparse_hybrid", "Sparse Hybrid"),
                        ],
                        default="dense",
                        max_length=20,
                    ),
                ),
                (
                    "param_scale",
                    models.CharField(
                        blank=True, help_text="e.g. 8B parameters", max_length=50
                    ),
                ),
                (
                    "context_length",
                    models.CharField(
                        blank=True, help_text="e.g. 128K tokens", max_length=50
                    ),
                ),
                (
                    "attention_type",
                    models.CharField(
                        blank=True, help_text="e.g. GQA + RoPE", max_length=100
                    ),
                ),
                (
                    "normalization",
                    models.CharField(
                        blank=True, help_text="e.g. RMSNorm (Pre-Norm)", max_length=100
                    ),
                ),
                (
                    "activation",
                    models.CharField(
                        blank=True, help_text="e.g. SiLU (SwiGLU)", max_length=100
                    ),
                ),
                (
                    "position_encoding",
                    models.CharField(blank=True, help_text="e.g. RoPE", max_length=100),
                ),
                ("vocab_size", models.CharField(blank=True, max_length=50)),
                ("hidden_dim", models.CharField(blank=True, max_length=50)),
                ("num_layers", models.CharField(blank=True, max_length=50)),
                ("num_heads", models.CharField(blank=True, max_length=50)),
                (
                    "num_experts",
                    models.CharField(
                        blank=True,
                        help_text="전문가 수 (dense 모델은 비워둠)",
                        max_length=50,
                    ),
                ),
                ("active_experts", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True, help_text="한글 설명")),
                (
                    "key_detail",
                    models.TextField(blank=True, help_text="핵심 특징 한줄 요약"),
                ),
                (
                    "training_detail",
                    models.TextField(blank=True, help_text="학습 관련 특이사항"),
                ),
                ("paper_url", models.URLField(blank=True)),
                ("code_url", models.URLField(blank=True)),
                ("license_type", models.CharField(blank=True, max_length=100)),
                (
                    "figure",
                    models.ImageField(
                        blank=True, null=True, upload_to="architectures/"
                    ),
                ),
                ("figure_placeholder", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concepts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="entries",
                        to="blog.architectureconcept",
                    ),
                ),
                (
                    "related_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="architecture_entries",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "architecture entries",
                "ordering": ["-release_date", "name"],
            },
        ),
    ]
