# Generated by Django 5.2.11 on 2026-03-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_architectureentry_tree_fields_and_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="architectureentry",
            name="activation",
            field=models.CharField(
                blank=True, help_text="e.g. SiLU (SwiGLU)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="active_experts",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="attention_type",
            field=models.CharField(
                blank=True, help_text="e.g. GQA + RoPE", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="context_length",
            field=models.CharField(
                blank=True, help_text="e.g. 128K tokens", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="hidden_dim",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="normalization",
            field=models.CharField(
                blank=True, help_text="e.g. RMSNorm (Pre-Norm)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="num_experts",
            field=models.CharField(
                blank=True, help_text="전문가 수 (dense 모델은 비워둠)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="num_heads",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="num_layers",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="param_scale",
            field=models.CharField(
                blank=True, help_text="e.g. 8B parameters", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="position_encoding",
            field=models.CharField(blank=True, help_text="e.g. RoPE", max_length=200),
        ),
        migrations.AlterField(
            model_name="architectureentry",
            name="vocab_size",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
