# Generated by Django 5.2.11 on 2026-03-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_architectureentry_activation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="게시판 목록에 표시할 표지 이미지",
                null=True,
                upload_to="posts/covers/",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(default=False, help_text="목록 상단 고정"),
        ),
        migrations.CreateModel(
            name="PostLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_text",
                    models.CharField(help_text="원본 [[텍스트]]", max_length=255),
                ),
                (
                    "context",
                    models.TextField(blank=True, help_text="링크가 사용된 주변 문맥"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_links",
                        to="blog.post",
                    ),
                ),
                (
                    "to_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_links",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_post", "to_post")},
            },
        ),
    ]
