# Generated by Django 5.2.11 on 2026-03-22 15:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_add_cover_image_is_pinned"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimage",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.AddField(
            model_name="postimage",
            name="caption",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="postimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("general", "일반"),
                    ("paper_figure", "논문 Figure"),
                    ("code_output", "코드 실행 결과"),
                    ("diagram", "다이어그램"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="postimage",
            name="source_ref",
            field=models.CharField(
                blank=True, help_text="e.g. Figure 3 from [Paper]", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="postimage",
            name="image",
            field=models.ImageField(upload_to=blog.models.dynamic_upload_path),
        ),
    ]
