# Generated by Django 5.2.11 on 2026-03-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_blog_post_author__95cbf7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="추가 카테고리 (다중 분류)",
                related_name="cross_posts",
                to="blog.category",
            ),
        ),
    ]
