# Generated by Django 5.2.12 on 2026-03-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('docker', 'Docker'), ('lxd', 'LXD'), ('general', 'General')], default='aws', max_length=20)),
                ('service_domain', models.CharField(choices=[('compute', 'Compute'), ('storage', 'Storage'), ('database', 'Database'), ('networking', 'Networking'), ('security', 'Security'), ('analytics', 'Analytics'), ('ai_ml', 'AI/ML'), ('devtools', 'DevTools'), ('management', 'Management'), ('integration', 'Integration'), ('container', 'Container'), ('devops', 'DevOps')], max_length=20)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('is_serverless', models.BooleanField(default=False)),
                ('is_managed', models.BooleanField(default=True)),
                ('pricing_model', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('key_detail', models.TextField(blank=True)),
                ('use_cases', models.TextField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('importance', models.IntegerField(default=5)),
                ('tree_x', models.FloatField(blank=True, null=True)),
                ('tree_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_service_entries', to='blog.post')),
            ],
            options={
                'verbose_name_plural': 'cloud service entries',
                'ordering': ['service_domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CloudServiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('integrates_with', 'Integrates'), ('depends_on', 'Depends On'), ('alternative_to', 'Alternative'), ('part_of', 'Part Of'), ('evolved_from', 'Evolved From')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='blog.cloudserviceentry')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='blog.cloudserviceentry')),
            ],
            options={
                'unique_together': {('from_service', 'to_service', 'relation_type')},
            },
        ),
    ]
